### Numpy

In [1]:
# gotta import numpy

import numpy as np

In [4]:
# creating a list

mylist = [1,2,3]

In [5]:
# checking the type

type(mylist)

list

In [6]:
# 

np.array(mylist)

array([1, 2, 3])

In [7]:
# mylist is still there

mylist

[1, 2, 3]

In [8]:
# assign mylist to myarr

myarr = np.array(mylist)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
type(my_matrix)

list

In [14]:
# numpy recognizes that this is two-dimensional

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# the equivalent of python's range function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# adding a specified step size

np.arange(0, 50, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [17]:
# a one-dimensional vector of zeroes

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# creating a two-dimensional array

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# returns a specified amount of evenly-spaced numbers over a specified interval (endpoint included)

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# creates in identity matrix (one number species the columns and rows)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### creating random distibutions of data

In [ ]:
# creates an array of the given shape and populates it with random samples from a uniform distribution

