### Numpy

In [1]:
# gotta import numpy

import numpy as np

In [4]:
# creating a list

mylist = [1,2,3]

In [5]:
# checking the type

type(mylist)

list

In [6]:
# 

np.array(mylist)

array([1, 2, 3])

In [7]:
# mylist is still there

mylist

[1, 2, 3]

In [8]:
# assign mylist to myarr

myarr = np.array(mylist)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
type(my_matrix)

list

In [14]:
# numpy recognizes that this is two-dimensional

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# the equivalent of python's range function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# adding a specified step size

np.arange(0, 50, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [17]:
# a one-dimensional vector of zeroes

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
# creating a two-dimensional array

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# returns a specified amount of evenly-spaced numbers over a specified interval (endpoint included)

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# creates in identity matrix (one number species the columns and rows)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### creating random distibutions of data

In [26]:
# creates an array of the given shape and populates it with random samples from a uniform distribution

np.random.rand(1)

array([0.20900007])

In [27]:
np.random.rand(6,2)

array([[0.11237641, 0.66198542],
       [0.59019829, 0.92771333],
       [0.05843643, 0.40357567],
       [0.07111688, 0.64541194],
       [0.56121645, 0.08008004],
       [0.87444321, 0.70941906]])

In [28]:
# creating samples from a standard normal distribution (mean 0 and variance 1)

np.random.randn(8)

array([ 1.37465733,  0.21285491, -1.04926336, -0.44248757,  3.23511576,
        0.44679447, -0.69256879,  0.7301613 ])

In [29]:
np.random.randn(2,3)

array([[-0.86182246, -0.06511999, -0.79842886],
       [-0.96599995,  0.65143874, -1.50209235]])

In [31]:
# returns whole integer numbers (higher threshold is exclusive)

np.random.randint(0,101, 6)

array([ 2, 62, 45, 92, 43, 22])

In [32]:
np.random.randint(0,101,(4,5))

array([[29, 20,  9, 56, 12],
       [99, 80, 14, 72, 40],
       [21,  7, 22, 96,  7],
       [27,  3, 63, 55, 27]])

In [33]:
# setting the seed for repeatability / seed must be in the same cell
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
# to reshape an array, first initialize it

arr = np.arange(0,20)

In [35]:
# now you can reshape

arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
ranarr = np.random.randint(0,101,8)

In [40]:
ranarr

array([21, 52,  1, 87, 29, 37,  1, 63])

In [41]:
ranarr.max()

87

In [42]:
ranarr.min()

1

In [43]:
# to find the index number that is greatest, use argmax

ranarr.argmax()

3

In [44]:
ranarr.argmin()

2

In [45]:
# determine the data type of an array with the attribute, dtype

ranarr.dtype

dtype('int64')

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
# find out the shape with the attribute, shape

arr.shape

(20,)

In [48]:
arr = arr.reshape(4,5)

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
arr.shape

(4, 5)

### indexing and selection

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# searching by index

arr[8]

8

In [54]:
# end point is EXclusive

arr[1:5]

array([1, 2, 3, 4])

In [55]:
# omitting a start point means that you start from the beginning

arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
# same idea with omitting the stop point

arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
# broadcasting

arr[0:5] = 100

In [62]:
# the values have been reassigned

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
# reset

arr = np.arange(0,11)

In [66]:
# slicing acts as a pointer

slice_of_arr = arr[0:5]

In [67]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr[:] = 99

In [70]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [71]:
# checking the original

arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])